name = "Freeze"
uuid = "5ec2d65f-4743-4a68-a0d2-9e48020e74af"
authors = ["Andy Ferris <ferris.andy@gmail.com>"]
version = "0.1.0"

[deps]
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
